# Generated by Django 5.0.14 on 2026-07-30 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('SECURITY', 'Seguridad'), ('AUTHENTICATION', 'Autenticación'), ('USER_MANAGEMENT', 'Gestión de usuarios'), ('ROLE_MANAGEMENT', 'Gestión de roles'), ('PERMISSION_MANAGEMENT', 'Gestión de permisos'), ('DASHBOARD_ACCESS', 'Acceso a dashboard'), ('DASHBOARD_LAYOUT', 'Diseño de dashboard'), ('DASHBOARD_CONFIGURATION', 'Configuración de dashboard'), ('DATA_SOURCE', 'Fuente de datos'), ('EXPORT', 'Exportación'), ('FILE_UPLOAD', 'Carga de archivo'), ('SYSTEM_CONFIGURATION', 'Configuración del sistema')], db_index=True, max_length=30)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('result', models.CharField(choices=[('SUCCESS', 'Éxito'), ('FAILED', 'Fallido'), ('DENIED', 'Denegado'), ('WARNING', 'Advertencia')], db_index=True, default='SUCCESS', max_length=10)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], db_index=True, default='INFO', max_length=10)),
                ('actor_username', models.CharField(blank=True, default='', max_length=150)),
                ('entity_type', models.CharField(blank=True, default='', max_length=100)),
                ('entity_id', models.CharField(blank=True, default='', max_length=64)),
                ('entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('dashboard_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('component_id', models.CharField(blank=True, default='', max_length=100)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('session_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('previous_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('message', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
