# Generated by Django 5.0.14 on 2026-07-30 14:36

import apps.branding.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='Dashboard de Cartera', max_length=150)),
                ('short_name', models.CharField(blank=True, default='Cartera', max_length=50)),
                ('logo_url', models.CharField(blank=True, default='', max_length=500)),
                ('favicon_url', models.CharField(blank=True, default='', max_length=500)),
                ('color_primary', models.CharField(default='#2a78d6', max_length=7, validators=[apps.branding.validators.validate_hex_color])),
                ('color_secondary', models.CharField(default='#eb6834', max_length=7, validators=[apps.branding.validators.validate_hex_color])),
                ('color_background', models.CharField(default='#eeeeee', max_length=7, validators=[apps.branding.validators.validate_hex_color])),
                ('color_headings', models.CharField(default='#000000', max_length=7, validators=[apps.branding.validators.validate_hex_color])),
                ('color_text', models.CharField(default='#000000', max_length=7, validators=[apps.branding.validators.validate_hex_color])),
                ('color_links', models.CharField(default='#2a78d6', max_length=7, validators=[apps.branding.validators.validate_hex_color])),
                ('color_buttons', models.CharField(default='#2a78d6', max_length=7, validators=[apps.branding.validators.validate_hex_color])),
                ('color_menu', models.CharField(default='#ffffff', max_length=7, validators=[apps.branding.validators.validate_hex_color])),
                ('font_primary', models.CharField(default='system', max_length=20, validators=[apps.branding.validators.validate_font_slug])),
                ('font_secondary', models.CharField(default='system', max_length=20, validators=[apps.branding.validators.validate_font_slug])),
                ('font_size_base', models.CharField(default='16px', max_length=10, validators=[apps.branding.validators.validate_font_size])),
                ('border_radius', models.CharField(default='medium', max_length=20, validators=[apps.branding.validators.validate_border_radius_slug])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
