# Generated by Django 5.0.14 on 2026-07-30 20:18

import apps.branding.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branding', '0002_seed_default_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetheme',
            name='color_button_text',
            field=models.CharField(default='#ffffff', max_length=7, validators=[apps.branding.validators.validate_hex_color]),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='color_danger',
            field=models.CharField(default='#dc3545', max_length=7, validators=[apps.branding.validators.validate_hex_color]),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='color_info',
            field=models.CharField(default='#0dcaf0', max_length=7, validators=[apps.branding.validators.validate_hex_color]),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='color_success',
            field=models.CharField(default='#198754', max_length=7, validators=[apps.branding.validators.validate_hex_color]),
        ),
        migrations.AddField(
            model_name='sitetheme',
            name='color_warning',
            field=models.CharField(default='#ffc107', max_length=7, validators=[apps.branding.validators.validate_hex_color]),
        ),
    ]
