# Generated by Django 5.0.14 on 2026-07-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('usuarios.ver', 'Ver usuarios'), ('usuarios.crear', 'Crear usuarios'), ('usuarios.editar', 'Editar usuarios y su asignación de roles/permisos'), ('usuarios.deshabilitar', 'Habilitar, deshabilitar, bloquear y desbloquear usuarios'), ('usuarios.restablecer_password', 'Forzar cambio de contraseña o cerrar sesiones activas de un usuario'), ('roles.ver', 'Ver roles y el catálogo de permisos'), ('roles.editar', 'Crear, editar y eliminar roles'), ('permisos.ver', 'Ver el catálogo de permisos y a qué módulo pertenece cada uno'), ('configuracion.ver', 'Ver configuración del sistema'), ('configuracion.editar', 'Editar configuración del sistema'), ('auditoria.ver', 'Ver el registro de auditoría'), ('auditoria.ver_detalle', 'Ver el detalle (valores anteriores y nuevos) de un evento'), ('auditoria.exportar', 'Exportar el registro de auditoría'), ('dashboard.view', 'Ver el dashboard de cartera'), ('dashboard.edit', 'Entrar en modo edición del dashboard'), ('dashboard.layout.edit', 'Editar el diseño (orden/tamaño) del dashboard'), ('dashboard.component.style', 'Editar estilos de un componente del dashboard'), ('dashboard.component.create', 'Crear componentes del dashboard'), ('dashboard.component.delete', 'Eliminar componentes del dashboard'), ('dashboard.configuration.reset', 'Restablecer la configuración del dashboard')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
