# Generated by Django 5.0.14 on 2026-07-31 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0002_alter_modulepermission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulepermission',
            options={'default_permissions': (), 'managed': False, 'permissions': [('usuarios.ver', 'Ver usuarios'), ('usuarios.crear', 'Crear usuarios'), ('usuarios.editar', 'Editar usuarios y su asignación de roles/permisos'), ('usuarios.deshabilitar', 'Habilitar, deshabilitar, bloquear y desbloquear usuarios'), ('usuarios.restablecer_password', 'Forzar cambio de contraseña o cerrar sesiones activas de un usuario'), ('roles.ver', 'Ver roles y el catálogo de permisos'), ('roles.editar', 'Crear, editar y eliminar roles'), ('permisos.ver', 'Ver el catálogo de permisos y a qué módulo pertenece cada uno'), ('configuracion.ver', 'Ver configuración del sistema'), ('configuracion.editar', 'Editar configuración del sistema'), ('auditoria.ver', 'Ver el registro de auditoría'), ('auditoria.ver_detalle', 'Ver el detalle (valores anteriores y nuevos) de un evento'), ('auditoria.exportar', 'Exportar el registro de auditoría'), ('dashboard.crear', 'Crear nuevos dashboards por área'), ('dashboard.editar', 'Editar el nombre y área de un dashboard'), ('dashboard.eliminar', 'Eliminar un dashboard'), ('dashboard.view', 'Ver el dashboard de cartera'), ('dashboard.edit', 'Entrar en modo edición del dashboard'), ('dashboard.layout.edit', 'Editar el diseño (orden/tamaño) del dashboard'), ('dashboard.component.style', 'Editar estilos de un componente del dashboard'), ('dashboard.component.create', 'Crear componentes del dashboard'), ('dashboard.component.delete', 'Eliminar componentes del dashboard'), ('dashboard.configuration.reset', 'Restablecer la configuración del dashboard')]},
        ),
    ]
