# Generated by Django 5.0.14 on 2026-07-29 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargaArchivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_original', models.CharField(max_length=255)),
                ('nombre_hoja', models.CharField(blank=True, max_length=255)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('SUBIDO', 'Subido'), ('VALIDADO', 'Validado'), ('PROCESADO', 'Procesado'), ('ERROR', 'Error')], default='SUBIDO', max_length=20)),
                ('fecha_corte', models.DateField(blank=True, null=True)),
                ('total_filas_excel', models.IntegerField(default=0)),
                ('filas_validas', models.IntegerField(default=0)),
                ('filas_advertencia', models.IntegerField(default=0)),
                ('filas_descartadas', models.IntegerField(default=0)),
                ('mapeo_columnas', models.JSONField(blank=True, default=dict)),
                ('resumen_validacion', models.JSONField(blank=True, default=dict)),
                ('archivo_temp_nombre', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='RegistroCartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(blank=True, default='', max_length=255)),
                ('ruc_cliente', models.CharField(blank=True, default='', max_length=50)),
                ('codigo_cliente', models.CharField(blank=True, default='', max_length=100)),
                ('identificador_cliente', models.CharField(db_index=True, max_length=255)),
                ('sucursal', models.CharField(blank=True, default='', max_length=255)),
                ('ciudad', models.CharField(db_index=True, default='SIN CIUDAD', max_length=255)),
                ('zona', models.CharField(blank=True, default='', max_length=255)),
                ('vendedor_ejecutivo', models.CharField(blank=True, default='', max_length=255)),
                ('estado_cliente', models.CharField(blank=True, default='', max_length=100)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('direccion', models.TextField(blank=True, default='')),
                ('numero_documento', models.CharField(db_index=True, default='', max_length=100)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, db_index=True, null=True)),
                ('saldo', models.DecimalField(db_index=True, decimal_places=2, max_digits=18)),
                ('articulo', models.CharField(blank=True, default='', max_length=255)),
                ('vence_original', models.CharField(blank=True, default='', max_length=100)),
                ('observacion', models.TextField(blank=True, default='')),
                ('mes', models.CharField(blank=True, default='', max_length=50)),
                ('tipo_venta', models.CharField(blank=True, default='', max_length=100)),
                ('causal', models.CharField(db_index=True, default='SIN GESTIÓN', max_length=100)),
                ('producto', models.CharField(blank=True, default='', max_length=255)),
                ('fecha_compromiso_pago', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('tipo_cartera', models.CharField(blank=True, default='', max_length=100)),
                ('recuperador', models.CharField(db_index=True, default='SIN RECUPERADOR ASIGNADO', max_length=255)),
                ('dias_credito', models.IntegerField(blank=True, null=True)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='cartera.cargaarchivo')),
            ],
            options={
                'indexes': [models.Index(fields=['carga', 'fecha_vencimiento'], name='cartera_reg_carga_i_635d5a_idx'), models.Index(fields=['carga', 'recuperador'], name='cartera_reg_carga_i_c1b23f_idx'), models.Index(fields=['carga', 'causal'], name='cartera_reg_carga_i_35cd0a_idx'), models.Index(fields=['carga', 'ciudad'], name='cartera_reg_carga_i_62cddf_idx')],
            },
        ),
    ]
