# Generated by Django 5.0.14 on 2026-07-29 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_id', models.SlugField(max_length=100)),
                ('component_id', models.SlugField(blank=True, default='', max_length=100)),
                ('change_type', models.CharField(choices=[('CAMBIO_DE_ORDEN', 'Cambio de orden'), ('CAMBIO_DE_TAMANO', 'Cambio de tamaño'), ('CAMBIO_DE_COLOR', 'Cambio de color'), ('CAMBIO_DE_TEXTO', 'Cambio de texto'), ('COMPONENTE_OCULTADO', 'Componente ocultado'), ('COMPONENTE_ELIMINADO', 'Componente eliminado'), ('DISENO_RESTABLECIDO', 'Diseño restablecido')], max_length=30)),
                ('changed_by', models.CharField(blank=True, default='Anónimo', max_length=150)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('previous_config', models.JSONField(blank=True, default=dict)),
                ('new_config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_id', models.SlugField(max_length=100, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('scope', models.CharField(choices=[('GENERAL', 'General'), ('POR_ROL', 'Por rol'), ('POR_USUARIO', 'Por usuario')], default='GENERAL', max_length=20)),
                ('theme', models.JSONField(blank=True, default=dict)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.SlugField(max_length=100)),
                ('type', models.CharField(choices=[('kpi', 'Tarjeta KPI'), ('chart', 'Gráfico'), ('filter', 'Filtro'), ('filters_panel', 'Panel de filtros'), ('message', 'Mensaje'), ('alert', 'Alerta'), ('table', 'Tabla'), ('title', 'Título'), ('text', 'Texto')], max_length=20)),
                ('chart_type', models.CharField(blank=True, default='', max_length=30)),
                ('row', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=1)),
                ('width', models.PositiveSmallIntegerField(default=12)),
                ('height', models.PositiveIntegerField(default=400)),
                ('is_visible', models.BooleanField(default=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('styles', models.JSONField(blank=True, default=dict)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='cartera.dashboardlayout')),
            ],
            options={
                'ordering': ['row', 'order'],
                'unique_together': {('layout', 'component_id')},
            },
        ),
    ]
