# Generated by Django 5.0.14 on 2026-07-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0002_dashboardauditlog_dashboardlayout_dashboardcomponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardauditlog',
            name='change_type',
            field=models.CharField(choices=[('CAMBIO_DE_ORDEN', 'Cambio de orden'), ('CAMBIO_DE_TAMANO', 'Cambio de tamaño'), ('CAMBIO_DE_COLOR', 'Cambio de color'), ('CAMBIO_DE_TEXTO', 'Cambio de texto'), ('CAMBIO_DE_CONFIGURACION', 'Cambio de configuración'), ('COMPONENTE_OCULTADO', 'Componente ocultado'), ('COMPONENTE_ELIMINADO', 'Componente eliminado'), ('DISENO_RESTABLECIDO', 'Diseño restablecido')], max_length=30),
        ),
    ]
