# Generated by Django 5.0.14 on 2026-08-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0006_eliminar_dashboard_cartera'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaarchivo',
            name='archivo_permanente_nombre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dashboardcomponent',
            name='mapeo',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
