# Generated by Django 5.0.14 on 2026-08-03 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0007_cargaarchivo_archivo_permanente_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='orden',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pestanas', to='cartera.dashboard'),
        ),
    ]
