# Generated by Django 5.0.14 on 2026-08-03 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _copiar_created_by_a_owner(apps, schema_editor):
    """`owner` nace igual a `created_by` para los dashboards que ya existían antes de este campo
    — evita que queden "sin dueño" de la nada. No cambia ningún comportamiento visible: el ACL por
    dashboard solo se activa cuando se le asignan roles explícitamente, nunca por tener dueño."""
    Dashboard = apps.get_model('cartera', 'Dashboard')
    Dashboard.objects.filter(created_by__isnull=False).update(owner=models.F('created_by'))


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cartera', '0008_dashboard_orden_dashboard_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards_propios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='roles_editores',
            field=models.ManyToManyField(blank=True, related_name='dashboards_como_editor', to='auth.group'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='roles_lectores',
            field=models.ManyToManyField(blank=True, related_name='dashboards_como_lector', to='auth.group'),
        ),
        migrations.RunPython(_copiar_created_by_a_owner, migrations.RunPython.noop),
    ]
