# Generated by Django 5.0.14 on 2026-08-04 20:03

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0009_dashboard_owner_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilaArchivoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('datos', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas_historicas', to='cartera.cargaarchivo')),
            ],
            options={
                'ordering': ['carga', 'orden'],
            },
        ),
    ]
