# Generated by Django 5.0.14 on 2026-08-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0012_backfill_tablas_historicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColumnaHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_id', models.SlugField(max_length=100)),
                ('columna', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['dashboard_id', 'columna'],
                'unique_together': {('dashboard_id', 'columna')},
            },
        ),
    ]
