# Generated by Django 5.0.14 on 2026-08-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0014_eliminar_tablas_4_y_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='contexto',
            field=models.TextField(blank=True, default=''),
        ),
    ]
