# Generated by Django 5.0.14 on 2026-08-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0015_dashboard_contexto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargaarchivo',
            name='incluir_en_historico',
            field=models.BooleanField(default=True),
        ),
    ]
