# Generated by Django 5.0.14 on 2026-08-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0016_cargaarchivo_incluir_en_historico'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='fuente_bd_nombre',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='fuente_bd_tipo',
            field=models.CharField(blank=True, choices=[('vista', 'Vista'), ('procedimiento', 'Procedimiento almacenado')], default='', max_length=20),
        ),
    ]
