# Generated by Django 5.0.14 on 2026-08-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0017_dashboard_fuente_bd'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='fuente_bd_parametros',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
