# Generated by Django 5.0.14 on 2026-08-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0018_dashboard_fuente_bd_parametros'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='fuente_bd_fecha_configuracion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='fuente_bd_frecuencia_actualizacion',
            field=models.CharField(blank=True, choices=[('semanal', 'Semanal (todos los domingos)'), ('mensual', 'Mensual (mismo día del mes)')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='fuente_bd_ultima_actualizacion_automatica',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='fuente_bd_ultimo_aliases',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='fuente_bd_ultimo_mapeo',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
