# Generated by Django 5.0.14 on 2026-08-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0019_dashboard_fuente_bd_scheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='fuente_bd_fecha_formato',
            field=models.CharField(blank=True, choices=[('YYYY-MM-DD', 'AAAA-MM-DD (2026-07-31)'), ('DD/MM/YYYY', 'DD/MM/AAAA (31/07/2026)'), ('MM/DD/YYYY', 'MM/DD/AAAA (07/31/2026)'), ('YYYY-MM-DD HH:mm:ss', 'AAAA-MM-DD HH:mm:ss (2026-07-31 00:00:00)')], default='YYYY-MM-DD', max_length=30),
        ),
    ]
