# Generated by Django 5.2.17 on 2026-09-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0021_sembrar_cartera_dashboard_directorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='estructura_bloqueada',
            field=models.BooleanField(default=False),
        ),
    ]
