# Generated by Django 5.2.17 on 2026-09-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0022_estructura_bloqueada'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='estructura_fijada',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
